config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#top'
  post '/homes/guest_sign_in', to: 'homes#guest_sign_in'

  resources :users,only: [:show, :edit, :update] do
    collection do
      get :favorites
    end
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end


  resources :posts,only: [:create, :index, :show, :update, :destroy, :new, :edit] do
    resource :favorites, only: [:create, :destroy]
    resources :post_comments, only: [:create, :destroy]
  end

  get '/search' => 'search#search'

  get '/rank' => 'ranks#rank'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/brand_tag.rb
class BrandTag < ApplicationRecord
  belongs_to :post
  belongs_to :tag
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :post_images, dependent: :destroy
  accepts_attachments_for :post_images, attachment: :image

  enum genre: { ショートボード:0, ミッドレングス:1, ロングボード:2, ソフトボード:3, その他:4 }

  has_many :brand_tags, dependent: :destroy
  has_many :tags, through: :brand_tags

  has_many :favorites, dependent: :destroy
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  has_many :post_comments, dependent: :destroy
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post_image.rb
class PostImage < ApplicationRecord
  belongs_to :post
  attachment :image
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :brand_tags, dependent: :destroy, foreign_key: 'tag_id'
  has_many :posts, through: :brand_tags
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :post, dependent: :destroy
  attachment :profile_image

  has_many :favorites, dependent: :destroy
  has_many :favorite_posts, through: :favorites, source: :post
  has_many :post_comments, dependent: :destroy

  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followers, through: :reverse_of_relationships, source: :follower

  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followings, through: :relationships, source: :followed
  def follow(user_id)
    relationships.create(followed_id: user_id)
  end
  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end
  def following?(user)
    followings.include?(user)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def guest_sign_in
    user = User.find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "ゲスト"
    end
    sign_in user
    redirect_to root_path
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :ensure_user, only: [:edit, :update, :destroy]

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    @post.save
    redirect_to posts_path
  end

  def index
    @posts = params[:tag_id].present? ? Tag.find(params[:tag_id]).posts : Post   #------ブランドタグ一覧を表示する-------
    @posts = @posts.page(params[:page]).reverse_order
  end

  def show
    @post = Post.find(params[:id])
    @post_comment = PostComment.new
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    @post.update(post_params)
    redirect_to posts_path
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path
  end

  private

  def ensure_user
    @post = current_user.post
    @post = @post.find_by(params[:id])
    redirect_to post_path unless @post
  end

  def post_params
    params.require(:post).permit(:title, :body, :genre, :size, post_images_images: [], tag_ids: [])
  end
end

app/controllers/ranks_controller.rb
class RanksController < ApplicationController
  def rank
    @post_favorite_ranks = Post.find(Favorite.group(:post_id).order('count(post_id) desc').pluck(:post_id))
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @posts = @user.post.page(params[:page]).reverse_order
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to user_path(@user.id)
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :tall_weight, :introduction)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/helpers/ranks_helper.rb
module RanksHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/homes/_top-comment.html.erb
<div class="top-comment">
  <p>
    Any boardsはサーフボード共有アプリです。</br>
    ビギナーからプロまで、全てのサーファーに向けて作られています。</br>
    早速お気に入りのボードを世界中に自慢しましょう!
  </p>
  <% if user_signed_in? %>
    <!--ログイン後に表示するボタン-->
    <div class="btn bgleft"><span><%= link_to "ボードを探す", posts_path, class:"sign_btn" %></span></div>
  <% else %>
    <!--ログイン前に表示するボタン-->
    <div class="btn bgleft"><span><%= link_to "新規登録", new_user_registration_path, class:"sign_btn" %></span></div>
    <div class="btn bgleft"><span><%= link_to 'ゲストログイン', homes_guest_sign_in_path, method: :post, class:"sign_btn" %></span></div>
  <% end %>
</div>

app/views/homes/top.html.erb
<div id="top">
  <div id="theTarget">
    <div class="image1">
      <%= render 'top-comment' %>
    </div>
    <div class="image2">
      <%= render 'top-comment' %>
    </div>
    <div class="image3">
      <%= render 'top-comment' %>
    </div>
  </div>
</div>

app/views/ranks/rank.html.erb
<div class="rank-container">
  <h2 class="search-title">NICE! Ranking</h2>
  <!--同率順位表示のための初期値-->
  <% last_favorites = 0 %>
  <% j = 1 %>
  <!--値をlast_favoritesに保存-->
  <% @post_favorite_ranks.each.with_index(1) do |post, i| %>
    <div class="index-cantainer">
      <h3>
      <!--同率順位表示-->
      <% if i == 1 %>
        <% last_favorites = post.favorites.count %>
      <% end %>
      <!--last_favoritesとNICE数比べて同じなら同じ順位、違うなら次の順位表示-->
      <% if post.favorites.count != last_favorites %>
        <% j = i %>
        No.<%= j %>
        <p><%= post.favorites.count %>NICE!</p>
        <% last_favorites = post.favorites.count %>
      <% else %>
        <% last_favorites = post.favorites.count %>
        NO.<%= j %>
        <p><%= post.favorites.count %>NICE!</p>
      <% end %>
      <!--/-->
      </h3>
      <div class="index-image">
        <%= link_to post_path(post.id) do %>
          <% post.post_images.first(1).each do |post_image| %>
        　　<%= attachment_image_tag post_image, :image, size: "200x200" %>
        　<% end %>
        <% end %>
      </div>

      <div class="index-details">
        <p class="index-text">ボードモデル：<%= post.title %></p>
        <p class="index-text">ユーザー：<%= link_to post.user.name, user_path(post.user_id), class:"index-user" %></p>
        <p class="index-text">ジャンル：<%= post.genre %></p>
        <p class="index-text">コメント件数：<%= post.post_comments.count %></p>
        <!--お気に入り機能-->
        <div id="post-favorite_<%= post.id %>">
          <%= render 'posts/post-favorite', post: post %>
        </div>
      </div>
    </div>
  <% end %>
</div>