config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#top'
  post '/homes/guest_sign_in', to: 'homes#guest_sign_in'

  resources :users,only: [:show, :edit, :update] do
    collection do
      get :favorites
    end
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end


  resources :posts,only: [:create, :index, :show, :update, :destroy, :new, :edit] do
    resource :favorites, only: [:create, :destroy]
    resources :post_comments, only: [:create, :destroy]
  end

  get '/search' => 'search#search'

  get '/rank' => 'ranks#rank'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/brand_tag.rb
class BrandTag < ApplicationRecord
  belongs_to :post
  belongs_to :tag
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :post_images, dependent: :destroy
  accepts_attachments_for :post_images, attachment: :image

  enum genre: { ショートボード:0, ミッドレングス:1, ロングボード:2, ソフトボード:3, その他:4 }

  has_many :brand_tags, dependent: :destroy
  has_many :tags, through: :brand_tags

  has_many :favorites, dependent: :destroy
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  has_many :post_comments, dependent: :destroy
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post_image.rb
class PostImage < ApplicationRecord
  belongs_to :post
  attachment :image
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :brand_tags, dependent: :destroy, foreign_key: 'tag_id'
  has_many :posts, through: :brand_tags
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :post, dependent: :destroy
  attachment :profile_image

  has_many :favorites, dependent: :destroy
  has_many :favorite_posts, through: :favorites, source: :post
  has_many :post_comments, dependent: :destroy

  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followers, through: :reverse_of_relationships, source: :follower

  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followings, through: :relationships, source: :followed
  def follow(user_id)
    relationships.create(followed_id: user_id)
  end
  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end
  def following?(user)
    followings.include?(user)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def guest_sign_in
    user = User.find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "ゲスト"
    end
    sign_in user
    redirect_to root_path
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :ensure_user, only: [:edit, :update, :destroy]

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    @post.save
    redirect_to posts_path
  end

  def index
    @posts = params[:tag_id].present? ? Tag.find(params[:tag_id]).posts : Post   #------ブランドタグ一覧を表示する-------
    @posts = @posts.page(params[:page]).reverse_order
  end

  def show
    @post = Post.find(params[:id])
    @post_comment = PostComment.new
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    @post.update(post_params)
    redirect_to posts_path
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path
  end

  private

  def ensure_user
    @post = current_user.post
    @post = @post.find_by(params[:id])
    redirect_to post_path unless @post
  end

  def post_params
    params.require(:post).permit(:title, :body, :genre, :size, post_images_images: [], tag_ids: [])
  end
end

app/controllers/ranks_controller.rb
class RanksController < ApplicationController
  def rank
    @post_favorite_ranks = Post.find(Favorite.group(:post_id).order('count(post_id) desc').pluck(:post_id))
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def search
    @model = params["search"]["model"]
    @value = params["search"]["value"]
    @datas = search_for(@model, @value)
  end

  private

  def search_for(model, value)
    #-------------------ユーザー名部分一致検索----------------------
    if model == 'user'
      User.where("name LIKE ?", "%#{value}%")
    #-------------------投稿タイトル部分一致検索--------------------
    elsif model == 'post'
      Post.where("title LIKE ?", "%#{value}%").page(params[:page]).reverse_order
    #-------------------ジャンル完全一致検索------------------------
    else
      Post.where(genre: value).page(params[:page]).reverse_order
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @posts = @user.post.page(params[:page]).reverse_order
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to user_path(@user.id)
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :tall_weight, :introduction)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/helpers/ranks_helper.rb
module RanksHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/posts/_post-favorite.html.erb
<% if post.favorited_by?(current_user) %>
<p>
  <%= link_to post_favorites_path(post), method: :delete, remote: true do %>
    <div class="btn-show bgcentery"><span class="sign_btn">NICE!<%= post.favorites.count %></span></div>
  <% end %>
</p>
<% else %>
<p>
  <%= link_to post_favorites_path(post), method: :post, remote: true do %>
    <div class="btn-show bgcentery"><span class="sign_btn">NICE!<%= post.favorites.count %></span></div></br>
  <% end %>
</p>
<% end %>

app/views/posts/_post-form.html.erb
<div class="container">
  <div class="form-container">
    <div class="post-form">
      <%= form_with model: post, local: true do |f| %>
      <div class="form-detail">
      　<%= f.label :"ボードのモデル", class:"form-label" %>
      　<%= f.text_field :title, placeholder:"例）CI MID", class:"form-input" %>
      </div>
      <div class="form-detail">
      　<%= f.label :"ボードの説明", class:"form-label" %>
      　<%= f.text_area :body, placeholder:"例）フィンシステム・おすすめのフィンセッティング・乗り心地・おすすめのサーファーのレベル　etc..", class:"form-input-introduction" %>
      </div>
      <div class="form-detail">
      　<%= f.label :"ボードのサイズ・浮力", class:"form-label" %>
      　<%= f.text_field :size, placeholder:"○.○ft / ○○L", class:"form-input" %>
      </div>
      <div class="form-detail">
      　<%= f.label :"ボードの画像", class:"form-label" %>
      　<%= f.attachment_field :post_images_images, multiple: true, class:"form-image" %>
      　<p>画像を複数投稿する際は、Shiftキーを押しながらマウスでクリックして選択してください。</p>
      </div>
      <div class="form-detail">
      　<%= f.label :"ジャンル", class:"form-label" %>
      　<%= f.select :genre, [["ショートボード"],["ミッドレングス"],["ロングボード"],["ソフトボード"],["その他"]], {}, {class: "select-input"} %>
      </div>
      <div class="form-detail">
      　<%= f.label :"ブランド", class:"form-label" %>
      　<div class="form-brand">
        <%= f.select :tag_id,options_from_collection_for_select(Tag.all, :id, :tag_name, params[:tag_id]), {}, {class: "select-input"} %>
        </div>
      </div>
      <div class="form-detail">
        <%= f.submit :"POST", class:"post-form-control"  %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/_post-index.html.erb
<div class="container">
    <% posts.each do |post| %>
    <div class="index-cantainer">
      <div class="index-image">
        <%= link_to post_path(post.id) do %>
          <% post.post_images.first(1).each do |post_image| %>
        　　<%= attachment_image_tag post_image, :image, size: "200x200" %>
        　<% end %>
        <% end %>
      </div>

      <div class="index-details">
        <p class="index-text">ボードモデル：<%= post.title %></p>
        <p class="index-text">ユーザー：<%= link_to post.user.name, user_path(post.user_id), class:"index-user" %></p>
        <p class="index-text">ジャンル：<%= post.genre %></p>
        <p class="index-text">コメント件数：<%= post.post_comments.count %></p>
        <!--お気に入り機能-->
        <div id="post-favorite_<%= post.id %>">
          <%= render 'posts/post-favorite', post: post %>
        </div>
      </div>
    </div>
    <% end %>
    <%= paginate posts %>
</div>

app/views/posts/edit.html.erb
<h2 class="post-title">POST編集</h2>
<!--投稿フォーム-->
<%= render 'post-form', post: @post %>

app/views/posts/index.html.erb
<div class="search-container">
  <div class="search-contents">
    <!--ブランドタグ検索フォーム-->
    <div class="brand-search">
      <p>ブランドで検索</p>
      <%= form_tag posts_path, method: :get, class: 'boards__searchForm' do %>
        <%= select_tag :tag_id,options_from_collection_for_select(Tag.all, :id, :tag_name, params[:tag_id]),
          { prompt: "ブランドで絞り込む",onchange: 'submit(this.form);', class:"select-input"}
        %>
      <% end %>
    </div>
    <!--キーワード検索フォーム-->
    <div class="keyword-search">
    <p>キーワードで検索</p>
    <% if user_signed_in? %>
      <%= form_with url:search_path, method: :get, local: true do |f| %>
        <%= f.select 'search[model]', options_for_select({ "ユーザーをキーワード検索" => "user", "ボード名をキーワード検索" => "post" }), {}, {class: "select-input"} %>
        <%= f.text_field 'search[value]', placeholder:"キーワードを入力", class:"form-input" %>
        <%= f.submit :"検索", class:"search-submit" %>
      <% end %>
    <% end %>
    </div>
    <!--ジャンル検索フォーム-->
    <div class="genre-search">
      <p>ボードの種類で検索</p>
    <% if user_signed_in? %>
      <%= form_with url:search_path, method: :get, local: true do |f| %>
        <%= f.select 'search[value]', [["ショートボード"],["ミッドレングス"],["ロングボード"],["ソフトボード"],["その他"]], {}, {class: "select-input"} %>
        <%= f.submit :"検索", class:"search-submit" %>
      <% end %>
    <% end %>
    </div>
  </div>
</div>
<!--投稿フォームへのリンクボタン-->
<div class="post-btn">
  <div class="btn-show bgcentery"><span><%= link_to "POST", new_post_path, class:"sign_btn" %></span></div>
</div>
<!--ランキングへのリンクボタン-->
<div class="post-btn">
  <div class="btn-show bgcentery"><span><%= link_to "Ranking", rank_path, class:"sign_btn" %></span></div>
</div>
<!--投稿一覧-->
<%= render 'post-index', posts: @posts %>

app/views/posts/new.html.erb
<h2 class="post-title">POST作成</h2>
<!--投稿フォーム-->
<%= render 'post-form', post: @post %>

app/views/posts/show.html.erb
<div class="container">
  <div class="show-title">
    <h2><%= @post.user.name %>'s　<%= @post.title %></h2>
    <!--お気に入り機能-->
    <div class="show-nice" id="post-favorite_<%= @post.id %>">
      <%= render 'posts/post-favorite', post: @post %>
    </div>
  </div>
  <div class="show-container">
    <div class="show-image">
      <% @post.post_images.each do |post_image| %>
      　<%= attachment_image_tag post_image, :image, class:"show-images" %>
      <% end %>
    </div>
    <div class="show-contents">
      <div class="show-details">
        <p class="show-text">ボードモデル</p>
        <p class="show-text bold"><%= @post.title %></p>
        <p class="show-text">ジャンル</p>
        <p class="show-text bold"><%= @post.genre %></p>
        <p class="show-text">ブランド</p>
          <% @post.tags.each do |tag| %>
            <p class="show-text bold"><%= tag.tag_name %></p>
          <% end %>
        <p class="show-text">サイズ・浮力</p>
        <p class="show-text bold"><%= @post.size %></p>
        <p class="show-text">身長・体重</p>
        <p class="show-text bold"><%= @post.user.tall_weight %></p>
        <p class="show-text">ユーザー</p>
        <p class="show-text bold"><%= link_to @post.user.name, user_path(@post.user_id) %></p>
        <p class="show-text">詳細</p>
        <p class="show-text bold"><%= @post.body %></p>
        <!--削除ボタン-->
        <% if @post.user == current_user %>
          <p class="show-text"><%= link_to "Destroy", post_path(@post), method: :delete, class:"destroy" %></p>
        <% end %>
        <!--編集画面へのリンクボタン-->
        <% if @post.user == (current_user) %>
          <div class="btn-show bgcentery"><span><%= link_to "Edit", edit_post_path(@post), class:"sign_btn" %></span></div>
        <% end %>
      </div>
    </div>
  </div>

  <!--コメント機能-->
  <div class="comment">
    <div class="comment-title">
      <h2>コメント</h2>
      <p class="comment-count">(<%= @post.post_comments.count %>)</p>
    </div>
    <div class="comment-contents">
      <% @post.post_comments.each do |post_comment| %>
      <div class="comment-index">
        <p class="comment-icon"><%= attachment_image_tag post_comment.user, :profile_image, :fill, 40, 40, fallback: "img/no_image.jpg", class:"profile-image"%></p>
        <p class="comment-details"><%= post_comment.user.name %></p>
        <p class="comment-details"><%= post_comment.created_at.strftime('%Y/%m/%d') %></p>
        <p class="comment-body"><%= post_comment.comment %></p>
        <div class="comment-details">
          <% if post_comment.user == current_user %>
            <%= link_to "削除", post_post_comment_path(post_comment.post, post_comment), method: :delete %>
          <% end %>
        </div>
      </div>
      <% end %>
    </div>
  </div>
  <div class="comment-new">
    <%= form_with(model:[@post, @post_comment], local: true) do |f| %>
      <%= f.text_area :comment, rows:'5',placeholder: "コメントをここに", class:"comment-form" %>
      <%= f.submit "送信する", class:"comment-submit" %>
    <% end %>
  </div>
</div>

app/views/users/edit.html.erb
<div class="container">
  <div class="edit-profile-container">
    <div class="edit-profile-form">
      <h2 class="edit-profile-title">プロフィール編集</h2>
      <%= form_with model:@user, local:true do |f| %>
      <div class="form-detail">
        <%= f.label :"ユーザーネーム", class:"form-label" %>
        <%= f.text_field :name, autofocus: true, placeholder:"ユーザーネームを入力", class:"form-input", placeholder:"名前"%>
      </div>
      <div class="form-detail">
        <%= f.label :"身長・体重", class:"form-label" %>
        <%= f.text_field :tall_weight, autofocus: true, placeholder:"○○○cm / ○○kg", class:"form-input", placeholder:"○○○cm/○○kg"%>
      </div>
      <div class="form-detail">
        <%= f.label :"プロフィール画像", class:"form-label" %>
        <%= attachment_image_tag @user, :profile_image, :fill, 400, 400, fallback: "img/no_image.jpg", class:"edit-profile-image"%>
        <%= f.attachment_field :profile_image, class:"form-image" %>
      </div>
      <div class="form-detail">
        <%= f.label :"自己紹介", class:"form-label" %>
        <%= f.text_area :introduction, autofocus: true, placeholder:"例）出身・ホームポイント・好きなサーファーetc..", class:"form-input-introduction" %>
      </div>
      <div class="form-detail">
        <%= f.submit "変更を保存", class:"form-input" %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/favorites.html.erb
<div class="container">
  <h2 class="favorite-title">NICE!一覧</h2>
  <% current_user.favorite_posts.each do |post| %>
    <div class="index-cantainer">
      <div class="index-image">
        <%= link_to post_path(post.id) do %>
          <% post.post_images.first(1).each do |post_image| %>
        　　<%= attachment_image_tag post_image, :image, size: "200x200" %>
        　<% end %>
        <% end %>
      </div>

      <div class="index-details">
        <p class="index-text">ボードの名前：<%= post.title %></p>
        <p class="index-text">ユーザーネーム：<%= link_to post.user.name, user_path(post.user_id), class:"index-user" %></p>
        <p class="index-text">ジャンル：<%= post.genre %></p>
        <p class="index-text">コメント件数：<%= post.post_comments.count %></p>
        <!--お気に入り機能-->
        <div id="post-favorite_<%= post.id %>">
          <%= render 'posts/post-favorite', post: post %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="profile-container">
    <div class="profile-contents">
      <div class="profile-title">
        <h1>Profile</h1>
        <% if @user == (current_user) %>
          <div class="btn-show bgcentery"><span><%= link_to "Edit", edit_user_path(@user), class:"sign_btn" %></span></div>
        <% else %>
          <% if current_user.following?(@user) %>
            <div class="btn-show bgcentery"><span><%= link_to "Unfollow", user_relationships_path(@user.id), method: :delete, class:"sign_btn" %></span></div>
          <% else %>
            <div class="btn-show bgcentery"><span><%= link_to "Follow", user_relationships_path(@user.id), method: :post, class:"sign_btn" %></span></div>
          <% end %>
        <% end %>
      </div>

      <div class="profile-icon">
        <%= attachment_image_tag @user, :profile_image, :fill, 200, 200, fallback: "img/no_image.jpg", class:"profile-image" %>
      </div>

      <div class="profile-details">
        <h3 class="profile-text"><%= @user.name %></h3>
        <p class="profile-text">性別：<%= @user.gender %></p>
        <p class="profile-text">身長・体重：<%= @user.tall_weight %></p>
        <div class="user-introduction">
          <P>自己紹介</P>
          <%= @user.introduction %>
        </div>
      </div>

      <div class="profile-link">
        <% if @user == (current_user) %>
          <p class="profile-text">NICE：<%= link_to "#{@user.favorites.count}", favorites_users_path(@user.id) %></p>
        <% else %>
          <p class="profile-text">NICE：<%= @user.favorites.count %>
        <% end %>
        <p class="profile-text">Follow：<%= link_to "#{@user.followings.count}", user_followings_path(@user.id) %></p>
        <p class="profile-text">Follower：<%= link_to "#{@user.followers.count}", user_followers_path(@user.id) %></p>
      </div>
    </div>
  </div>
  <!--投稿フォームへのリンクボタン-->
  <div class="post-btn">
    <div class="btn-show bgcentery"><span><%= link_to "POST", new_post_path, class:"sign_btn" %></span></div>
  </div>
  <!--投稿一覧-->
  <div class="post-index">
    <%= render 'posts/post-index', posts: @posts %>
  </div>
</div>